// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Board = require("./Board.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Score = require("./Score.js");
var React = require("react");
var Button = require("./Button.js");
var Js_math = require("bs-platform/lib/js/js_math.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var initialState = /* record */[
  /* score */0,
  /* status : Init */0,
  /* activeMole */-1,
  /* intervalId */undefined
];

var component = ReasonReact.reducerComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* status */1];
              return React.createElement("div", {
                          className: "app"
                        }, React.createElement("div", {
                              className: "game"
                            }, match ? React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, Score.make(self[/* state */1][/* score */0], /* array */[])), ReasonReact.element(undefined, undefined, Board.make(self[/* state */1][/* activeMole */2], (function (param) {
                                              return Curry._1(self[/* send */3], /* IncrementScore */1);
                                            }), /* array */[])), ReasonReact.element(undefined, undefined, Button.make("Reset", (function (_click) {
                                              return Curry._1(self[/* send */3], /* Reset */2);
                                            }), /* array */[]))) : ReasonReact.element(undefined, undefined, Button.make("Start Game!", (function (_click) {
                                          return Curry._1(self[/* send */3], /* Start */0);
                                        }), /* array */[]))));
            }),
          /* initialState */(function (param) {
              return initialState;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                switch (action) {
                  case 0 : 
                      return /* UpdateWithSideEffects */Block.__(2, [
                                /* record */[
                                  /* score */state[/* score */0],
                                  /* status : Started */1,
                                  /* activeMole */state[/* activeMole */2],
                                  /* intervalId */state[/* intervalId */3]
                                ],
                                (function (self) {
                                    var intervalId = setInterval((function (param) {
                                            var randomInt = Js_math.random_int(0, 9);
                                            return Curry._1(self[/* send */3], /* ChangeActiveMole */Block.__(0, [randomInt]));
                                          }), 1000);
                                    return Curry._1(self[/* send */3], /* AddIntervalId */Block.__(1, [Js_primitive.some(intervalId)]));
                                  })
                              ]);
                  case 1 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* score */state[/* score */0] + 1 | 0,
                                  /* status */state[/* status */1],
                                  /* activeMole */state[/* activeMole */2],
                                  /* intervalId */state[/* intervalId */3]
                                ]]);
                  case 2 : 
                      return /* Update */Block.__(0, [initialState]);
                  
                }
              } else if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* score */state[/* score */0],
                            /* status */state[/* status */1],
                            /* activeMole */state[/* activeMole */2],
                            /* intervalId */action[0]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* score */state[/* score */0],
                            /* status */state[/* status */1],
                            /* activeMole */action[0],
                            /* intervalId */state[/* intervalId */3]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.initialState = initialState;
exports.component = component;
exports.make = make;
/* component Not a pure module */
